import { getServerSession } from 'next-auth';

import { authOptions } from '@/pages/api/auth/[...nextauth]';
import { NavBar } from '@/app/components';

import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface Props {
  children: React.ReactNode;
}

const RootLayout = async ({ children }: Props) => {
  /* Fetch the user */
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className="mx-64">
        <NavBar user={session?.user} expires={session?.expires as string} />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
